version: '2'
services:
  wordpress_db:
    image: mysql:latest
    restart: always
    volumes:
          - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD:  wordpress
      MYSQL_DATABASE: boulders-local
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    image: wordpress:latest
    depends_on:
      - wordpress_db
    links:
      - wordpress_db
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: boulders-local
    volumes:
      - "./server/:/var/www/html"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - wordpress_db
    links:
      - wordpress_db:mysql
    ports:
      - 8181:80
    restart: always
    environment:
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      PMA_HOST: mysql
